/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package at.nieslony.arachne.tomcat;

import at.nieslony.arachne.Arachne;
import at.nieslony.arachne.settings.Settings;
import at.nieslony.arachne.settings.SettingsException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringWriter;
import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 *
 * @author claas
 */
@Service
public class TomcatService {

    @Value("${arachneConfigDir}")
    private String arachneConfigDir;

    @Autowired
    private Settings settings;

    private static final Logger logger = LoggerFactory.getLogger(TomcatService.class);

    public void saveApacheConfig(TomcatSettings tomcatSettings) {
        try {
            tomcatSettings.save(settings);
        } catch (SettingsException ex) {
            logger.error("Cannot save tomcat settings: " + ex.getMessage());
        }

        String fileName = arachneConfigDir + "/arachne.conf";
        String now = new Date().toString();
        StringWriter config = new StringWriter();
        config.write("# Generated by Arachne on %s\n\n".formatted(now));
        config.write("ProxyPass");
        config.write(" \"%s\" ".formatted(tomcatSettings.getAjpLocation()));
        config.write(" \"ajp://127.0.0.1:%d%s\""
                .formatted(
                        tomcatSettings.getAjpPort(),
                        tomcatSettings.getAjpLocation()));
        if (tomcatSettings.isEnableAjpSecret()) {
            config.write(" secret=" + tomcatSettings.getAjpSecret());
        }
        config.write("\n");

        try (FileWriter writer = new FileWriter(fileName)) {
            writer.write(config.toString());
        } catch (IOException ex) {
            logger.error("Cannot write %s: %s".formatted(fileName, ex.getMessage()));
        }

        Arachne.restart();
    }
}
